export const SET_CONTACT = 'set_contact'
export const SET_CONTACTS = 'set_contacts'
export const GET_CONTACTS = 'get_contacts'
export const UPDATE_CONTACT_NO_ANSWER = 'update_contact_no_answer'
export const GET_MESSAGES = 'get_messages'
export const SET_MESSAGES = 'set_messages'
export const SET_CURRENT_CONTACT = 'set_current_contact'

export const SET_ACCOUNT = 'set_account'
export const SET_ACCOUNTS_LIST = 'set_accounts_list'

export const SET_USERS = 'set_users'
export const SET_USER = 'set_user'
export const SET_PROMOCODES = 'set_promocodes'
export const SET_REFERRALS = 'set_referrals'
export const SET_CLIENTS = 'set_clients'
export const SET_REFERRALS_PAYMENTS = 'set_referrals_payments'
export const SET_AFFILIATE_PAYMENTS = 'set_affiliate_payments'
